spring:
  datasource:
    platform: init
    initialization-mode: always
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop

    show-sql: true
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    #org.hibernate: trace
    org.hibernate.event: trace

      #springframework.orm.jpa: trace

    #org.hibernate.type: TRACE

