spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/test?zeroDateTimeBehavior=convertToNull&useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    #url: r2dbc:pool:mysql://localhost:3306/test?zeroDateTimeBehavior=convertToNull&useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password:
    pool:
      max-create-connection-time: 2s
      initial-size: 25
      max-size: 50
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=convertToNull&useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    user: root
    password:
  web:
    resources.static-locations: file:src/main/resources/

logging:
  level:
    root: info
  #    org.springframework.data.r2dbc: DEBUG
#    org.springframework.r2dbc.R2dbcTransactionManager: debug # for transaction
#    org.springframework.r2dbc.core.DefaultDatabaseClient: debug # for query
#    org.springframework.r2dbc.connection: trace
#    om.github.jasync.sql.db.mysql: trace
#    io.r2dbc.pool: DEBUG
#    com.github.jasync.r2dbc: trace
    #org.flywaydb: trace