version: '3.1'

services:

  elasticsearch:
    container_name: es_db
    image: elasticsearch:6.4.0
    #restart: always
    environment:
      cluster.name: docker-cluster
      #bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300